name: test the workflow
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3
        
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
  test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
          
      - name:  Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          
      - name: test the Script
        run: |
          export PYTHONPATH=src
          pytest
